AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation sample template related to static website application

Resources:
  Ec2ApacheInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-05fa00d4c63e32376
      InstanceType: t2.micro
      KeyName: key-abbabe
      Tags:
        - Key: Name
          Value: Web Server of Kitten Carousel

     
      UserData:
        Fn::Base64:
          Fn::Join:
          - "\n"
          - - "#!/bin/bash "
            - sudo yum update -y
            - sudo yum install -y httpd.x86_64
            - systemctl start httpd.service
            - systemctl enable httpd.service
            - sudo chmod -R 777 var/www/html
            - cd var/www/html
            - 

      
      SecurityGroups:
        - Ref: ApacheSecurityGroups

  ApacheSecurityGroups:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: My Apache Security Group
      GroupName: My Apache SG

      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp:  "0.0.0.0/0"

      
        - IpProtocol: "tcp"
          FromPort: 443
          ToPort: 443
          CidrIp:  "0.0.0.0/0"

    
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp:  "0.0.0.0/0"


Outputs:
  URL:
    Description: URL of the sample website
    Value:
      Fn::Join: 
      - ''
      - - http://
        - Fn::GetAtt:
          - Ec2ApacheInstance
          - PublicDnsName