#SERVICE  for WEB-APP
apiVersion: v1
kind: Service  
metadata:
    name: web-app-service  # service name
    labels:  # Labels is important
      name: web-app-service # Name of service 
      app: myweb-app  # to connect between pod and services
spec:
  type: LoadBalancer # we wrote that for kubernetes 
  ports:
    - port: 80
      targetPort: 80  # external service port
     # nodePort: 30005

  #Selector 
  selector:
      name: web-app-pod
      app: myweb-app  # get from  web-app-pod.yaml  file  labels section.
